// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'btn--close': string;
  'btn--currency': string;
  'btn--display': string;
  'btn--primary': string;
  'btn--toggle': string;
}
export const cssExports: CssExports;
export default cssExports;
