// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'currency-display': string;
  'currency-display__main-currency': string;
  'currency-display__value': string;
  'currency-display__value--over': string;
  'currency-input': string;
  'currency-input--over': string;
}
export const cssExports: CssExports;
export default cssExports;
