// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'currencies-overlay': string;
  'currencies-overlay--open': string;
  'currencies-overlay__content': string;
  'currencies-overlay__content-recent': string;
  'currencies-overlay__header': string;
  'currencies-overlay__header--close': string;
}
export const cssExports: CssExports;
export default cssExports;
