// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'pocket': string;
  'pocket--flag': string;
}
export const cssExports: CssExports;
export default cssExports;
