// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'converter--content': string;
  'converter--content__action': string;
  'converter--content__additional': string;
  'converter--content__additional--toggle': string;
  'converter--content__from': string;
}
export const cssExports: CssExports;
export default cssExports;
